[project]
name = "test-quest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pyside6>=6.10.1",
]

[dependency-groups]
dev = [
    "black>=26.1.0",
    "ruff>=0.14.13",
]
[tool.ruff.lint]
select = ["E", "F"]
ignore = ["F401"]
